/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.danhieule.hack2019;

import processing.core.PApplet;

public class App extends PApplet {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        PApplet.main("org.danhieule.hack2019.App");
        PApplet.main("org.danhieule.hack2019.App");
    }

    public void settings() {
    	size(600, 600);
    }

    public void setup() {
    }
}


/*

build tool
C++, make
Java, Ant, Maven (pom.xml), Gradle (build.gradle)
Python, none

CI/CD server. CI = Continuous Integration, CD = Continuous Deployment
push code lên CI/CD server, sau đó nó sẽ compile code, chạy test, cho ra file .jar chạy được liền
notify mình

chọn build tool, chọn ide. Dùng ide để mà dùng build tool

*/